title: dummy-course
tagline: A brand new course on Learning Lab
description: Testing out learning lab
template:
  repo: dummy-course-template
  name: dummy-course
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
